### ISSUE TITLE
this._carousel.currentIndex is undefined

### ISSUE THREAD

**Issue by mazing** [archriss/react-native-snap-carousel#101] opened 2017-07-26 07:01 UTC
How can I store a state with the index of the currently active slide?

I have tried `this._carousel.currentIndex`, but I get the error `undefined is not an object (evaluating 'this._carousel.currentIndex')`.

I am setting the ref with

    <Carousel
      ref={carousel => { this._carousel = carousel; }}

**Comment by bd-arc** [comment] 2017-07-26 07:48
Hi @mazing,

Does this happen with version 2.4.0 or with the `FlatList` version?

**Comment by bd-arc** [comment] 2017-07-26 08:45
I've just tried the following and didn't face any issue:
```
<Carousel
  ref={(c) => { this._carousel = c; }}
/>

alert(this._carousel && this._carousel.currentIndex);
```

Are you positive that the `<Carousel />` is mounted when you call `this._carousel.currentIndex` the first time?

**Comment by itswaze** [comment] 2017-07-26 09:11
Using the alert on onSnapToItem shouldn't be firing the the alert everytime I swipe?

**Comment by itswaze** [comment] 2017-07-26 09:49
Im getting `undefined is not an objetct (evaluating 'this._carousel')` when running a function with `onSnapToItem`.

```
<Carousel
            ref={(carousel) => { this._carousel = carousel; }}
            onSnapToItem={this.updateIndex}
>
</Carousel>
```

Function:
```
  updateIndex(){
    Store.updateIndex(this._carousel.currentIndex)
  }
```

**Comment by bd-arc** [comment] 2017-07-26 14:16
@itswaze Did you make sure to bind `this` in your constructor? Something along those lines:
```
    constructor (props) {
        super(props);
        this.updateIndex = this.updateIndex.bind(this);
    }
```

**Comment by itswaze** [comment] 2017-07-28 13:34
Still didn't work...

**Comment by bd-arc** [comment] 2017-07-28 13:39
@itswaze I tried that myself and didn't have any issue. Could you please share the entire source code for your component?

**Comment by itswaze** [comment] 2017-07-28 14:03
Sure :)

Here is the relevant code: https://paste.ofcode.org/saNEHcfuwE2DKyQg49YaWy

What I want, is that when I press the X to go back, that the active slider that will show, was the last image I saw on the gallery.
Maybe I'm doing something wrong?

**Comment by bd-arc** [comment] 2017-07-28 16:19
@itswaze I totally get what you're trying to achieve, and I don't see anything wrong with your code...

Maybe the first call to `updateIndex` is triggered too soon because of `firstItem`? What if you guard against it this way:

**Comment by itswaze** [comment] 2017-07-28 16:55
Still nothing :( I'll keep trying to find out why is not working... Since it works for you it's not a problem of this library, so you can close the issue :)

Thank you!

**Comment by bd-arc** [comment] 2017-07-28 17:18
I haven't ruled out the possibility that it might come from the plugin, so I'll keep the issue opened for now ;-)

Can you try to import the relevant code step by step in the provided example? It might help figuring out what's going on.

**Comment by ali-sao** [comment] 2017-08-02 23:25
I am facing the same issue , I tried all your suggestions with no luck

**Comment by bd-arc** [comment] 2017-08-03 08:00
Hi @ali-sao,

If you can provide me with a simple example that reproduces the issue, I will gladly take a look at it. Since I can't reproduce it on my own, it might have something to do with how the data is handled, which is why I need a test case ;-)

Is the provided [example](https://github.com/archriss/react-native-snap-carousel/tree/master/example) working for you? Also, have you tried the [`flatlist` branch](https://github.com/archriss/react-native-snap-carousel/tree/flatlist)?

**Comment by ali-sao** [comment] 2017-08-03 10:29
Hey @bd-arc  and thanks for replying back , 

While I was trying to copy-paste the code to you , and for some weird reason , the error disappeared. and the pagination is working perfectly now , thank you.

**Comment by bd-arc** [comment] 2017-08-03 10:35
@ali-sao Good to know you've solved it, even though you and I would both appreciate to know how :-)

**Comment by ali-sao** [comment] 2017-08-03 10:37
Indeed , I will dig deep today to know why and how so this thread will be guide full for anyone with the same problem . 

Thanks again

**Closed** 2017-08-03 15:30 UTC
Labels: reproduction?

**Comment by hesusdios** [comment] 2018-09-27 22:31
Did you ever figure out what the issue was? I get the same problem.
My code is 

  _renderItem ({item, index}) {

        return (
            <TouchableOpacity onPress={() => this._carousel.snapToNext() }
            ><CircleList> </CircleList></TouchableOpacity>
        );
    }

  <Carousel layout={'default'}
                              ref={(c) => { this._carousel = c; }}
                              data={this.state.data}
                              sliderWidth={sliderWidth}
                              itemWidth={sliderWidth / 2}
                              enableSnap={false}
                              itemHeight={itemHeight / 3}
                              windowSize={1}
                              renderItem={this._renderItem}
                             

                    />

**Comment by jwan3453** [comment] 2018-11-14 09:41
@hesusdios , simply change the _renderItem to arrow function like    _renderItem = ({item, index}) => {} will solve the problem, or renderItem={this._renderItem.bind(this)}.

**Comment by hesusdios** [comment] 2018-11-14 10:06
Thanks I will try it out

**Comment by CarlosMayoralMX** [comment] 2019-11-12 07:16
> @hesusdios , simply change the _renderItem to arrow function like _renderItem = ({item, index}) => {} will solve the problem, or renderItem={this._renderItem.bind(this)}.

Actually after many tries this solution worked for me.Thanks

**Comment by venkataluri** [comment] 2019-11-22 12:59
Hi,

App is crashing with message 'carouselRef .getPositionIndex is not a function' when clicking on pagination dots

`const CarouselPage = ({navigation, ...props}) => {
    const [activePage, setActivePage] = useState(0);
    useEffect( () => { console.log(' active page : ', activePage)  }, [activePage] );
    
    let carouselRef = useRef(); // createRef()

        return(
           <Carousel
              ref={(c) => {carouselRef = c}}
                sliderWidth={screenWidth}
                sliderHeight={screenWidth}
                itemWidth={screenWidth}
                data={entries}
                renderItem={_renderItem}
                onSnapToItem={(index) => { setActivePage(index) }}
            />
             
            <Pagination
              dotsLength={entries.length}
              activeDotIndex={activePage}
              containerStyle={{ backgroundColor: 'rgba(0, 0, 0.6, 0.5)' }}
              dotStyle={{
                  width: 10,
                  height: 10,
                  borderRadius: 5,
                  marginHorizontal: 8,
                  backgroundColor: 'rgba(255, 255, 255, 0.92)'
              }}
              inactiveDotStyle={{
                  // Define styles for inactive dots here
              }}
              inactiveDotOpacity={0.4}
              inactiveDotScale={0.6}
              tappableDots={true}
              tappableDots={ !!carouselRef }
              carouselRef={ carouselRef }
            />
        );
};
`
can anyone help me in fixing this issue

**Comment by minhyuk0529** [comment] 2020-02-16 03:34
**For people using React-native Hook useRef**
Source :  https://reactjs.org/docs/hooks-reference.html#useref

> useRef returns a mutable ref object whose **.current property** is initialized to the passed argument (initialValue). The returned object will persist for the full lifetime of the component.

`const _carouselRef = useRef(null);`
then
`console.log(_carouselRef.current._activeItem)`

worked for me

**Comment by rotalex2000** [comment] 2021-06-09 11:15
The problem is that you try to use the currentIndex property of the carousel before the Carousel component is rendered and the reference is set.

Make carousel a state variable:
`const [carousel, setCarousel] = useState(null);`

and use `setCarousel()` to set it in the component.
`<Carousel
    ref={c => {
        setCarousel(c);
    }}
    ...
/>`

Then simply check for it's nullity everytime you use it, so that you catch the errors that might appear before the Carousel component loads and sets the reference.

**Comment by SpacePatrolDev** [comment] 2021-12-08 19:40
> The problem is that you try to use the currentIndex property of the carousel before the Carousel component is rendered and the reference is set.
> 
> Make carousel a state variable: `const [carousel, setCarousel] = useState(null);`
> 
> and use `setCarousel()` to set it in the component. `<Carousel ref={c => { setCarousel(c); }} ... />`
> 
> Then simply check for it's nullity everytime you use it, so that you catch the errors that might appear before the Carousel component loads and sets the reference.

This solution worked for me! Thanks
