### ISSUE TITLE
Invariant Violation: Listener is not supported for native driven events

### ISSUE THREAD

**Issue by nHiRanZ** [archriss/react-native-snap-carousel#289] opened 2018-03-20 12:36 UTC
Hi, I've been trying to implement the Snap Carousel with my app. But it gives the following warning and doesn't load up.

> Error: Listener is not supported for native driven events.
>     at invariant (invariant.js:38)
>     at new AnimatedEvent (AnimatedImplementation.js:2126)
>     at Object.event (AnimatedImplementation.js:2230)
>     at new Carousel (Carousel.js:147)
>     at ReactCompositeComponentWrapper._constructComponentWithoutOwner (ReactCompositeComponent.js:296)
>     at ReactCompositeComponentWrapper._constructComponent (ReactCompositeComponent.js:278)
>     at ReactCompositeComponentWrapper.mountComponent (ReactCompositeComponent.js:190)
>     at Object.mountComponent (ReactReconciler.js:47)
>     at Constructor.mountChildren (ReactMultiChild.js:240)
>     at Constructor.initializeChildren (ReactNativeBaseComponent.js:69)

The class with the carousel is as follows.

```
'use strict';

const styles = require('./Styles');
import React, {Component} from 'react';
import {
    View
} from 'react-native';

import Carousel from 'react-native-snap-carousel';

export default class CarouselCard extends Component {

    static renderItem({item, index}) {
        console.log(item);
        return item;
    }

    render() {
        return (
            <View key={this.props.cardKey}
                  style={[styles.cardContainer, {padding: 0, borderWidth: 0, marginRight: -10, marginLeft: -10}]}>
                <Carousel
                    ref={(c) => {
                        this._carousel = c;
                    }}
                    data={this.props.cardsList}
                    renderItem={CampaignCard.renderItem}
                    sliderWidth={this.props.sliderWidth}
                    itemWidth={this.props.itemWidth}
                    useScrollView={true}
                />
            </View>)
    }
}

```

And this component is used as following, in the parent class.

```
renderCarouselCards() {
        let topCardsList = [];

        for(let x = 0; x < this.state.campaigns.length; x++) {
            topCardsList.push(
                <CarouselCard
                    key={x}
                    cardKey={x}
                    cardsList={this.getTopCards(this.state.data[x])}
                    sliderWidth={Dimensions.get('window').width}
                    itemWidth={Dimensions.get('window').width - 20}
                />
            )
        }

        return topCardsList;
    }
```

Environment:
    React: 15.3.1
    React native: 0.37.0
    react-native-snap-carousel: 3.6.0

Target Platform:
    iOS (11.2)

Any workaround for this? Thank you.

**Comment by bd-arc** [comment] 2018-03-20 13:36
Hi @nHiRanZ,

You should take a look at #271 as it seems somewhat related.

If this doesn't help, you need to provide me with a [Snack](https://snack.expo.io/) example that reproduces the issue because the matter could be linked to something specific to your app.

**Comment by bd-arc** [comment] 2018-03-26 10:05
Closing as no further feedback was provided.

**Closed by bd-arc** 2018-03-26 10:05 UTC
Labels: reproduction?
