### ISSUE TITLE
Weird rendering last slide when loop is enable !

### ISSUE THREAD

**Issue by hugweb** [archriss/react-native-snap-carousel#194] opened 2017-10-20 12:42 UTC
Hi guys !

I'm experiencing a weird situation. When I reach the last slide when loop = true (both left or right side of the carousel) the next slide is display as a first slide : I believe according to the first state display on the first carousel rendering. This bug doesn't appear while sliding other pages.

Need to precise that I'm using children components inside pages which use the state property to change background color as you will see above.

Here is a gif to show you the problem :

![](https://i.imgur.com/BizBiWm.gif)

@bd-arc @Exilz any ideas?

**Comment by bd-arc** [comment] 2017-10-23 08:01
Hi @hugweb,

This is pretty strange, indeed. Does it work properly if you wait for the data to be retrieved before rendering the carousel? Something along those lines:

```
get loader () {
    return (
        <ActivityIndicator size={'small'} />
    );
}

get carousel () {
    const { items } = this.state;
    return (
        <Carousel data={items} />
    );
}

render () {
    const { items } = this.state;
    return !items.length ? this.loader : this.carousel;
}
```

**Comment by bd-arc** [comment] 2017-10-27 08:57
@hugweb Any news regarding the issue?

**Comment by hugweb** [comment] 2017-10-31 09:56
Sorry for the delay !

@bd-arc This is not link to loading the data before. I'n actually not loading anything. I'm just drawing pages changing the state of the **last page** then go to the **first page**  and come back to the **last** but the state is restore for 1 sec until it gets render back to the real state.

Maybe this is more explicit : 
![](https://media.giphy.com/media/l4EoV32fh7fFkoB7q/giphy.gif)

**Comment by bd-arc** [comment] 2017-10-31 10:31
@hugweb Hum, it might be linked to #199. I'll take a look at it as soon as I can.

In the meantime, I would really appreciate if you can share a minimal reproductible demo or a [Snack example](https://snack.expo.io/) ;-)

**Comment by bd-arc** [comment] 2017-11-01 22:35
The issue may have been fixed by the latest updates. To try it out, just copy/paste the following in your `package.json` file:
```
"react-native-snap-carousel": "https://github.com/archriss/react-native-snap-carousel#ce3bf06"
```

@hugweb Can you confirm that it works for you?

**Comment by hugweb** [comment] 2017-11-02 08:30
Looks like it's not working trying to do the Snack example today.

**Comment by hugweb** [comment] 2017-11-02 09:51
You can try this project : 

[bug-carousel.zip](https://github.com/archriss/react-native-snap-carousel/files/1437193/bug-carousel.zip)

Snack expo give a blank screen but code works perfectly on my laptop. Sorry I don't have time to understand why expo is not rendering properly, maybe the dependencies.

Let me know

**Comment by bd-arc** [comment] 2017-11-02 10:07
@hugweb Ok, thanks. I'll take a look at it as soon as possible.

**Comment by hugweb** [comment] 2017-11-06 08:38
@bd-arc Any news?

**Comment by bd-arc** [comment] 2017-11-06 08:55
Hi @hugweb,

I didn't have time to debug your project yet since I currently have pressing professional matters. As I said, as soon as I can ;-) (hopefully before the end of the week)

**Comment by bd-arc** [comment] 2017-11-08 19:10
@hugweb I took the time to test your example, but it didn't help me reproduce the issue. Here is a screencast that shows your example working the way it is supposed to:

![react-native-snap-carousel issue 194](https://i.imgur.com/DhWzq89.gif)

Still, I think I've understood what's troubling you. Correct me if I'm wrong, but you are updating elements on your slides and when looping, the clone slide is not up-to-date and the difference is seen for a split second. Is that it?

Unfortunately, I don't see any way of handling dynamic clones since all we can render in a `FlatList` component is an array of data. But maybe you can pass the dynamic updates as values to the array so that the duplicate slides can be kept in sync.

**Comment by hugweb** [comment] 2017-11-09 08:33
@bd-arc I'm not updating anything on loop. Each slide is a component and each component has his state. I update the state of the component by clicking on press me which change the color. Then when I slide between the last and the first slide (only when loop is enable) there is this glitch.

If you take a look, you can see that you can update the state of each component of each slide and it works perfectly for all slides except when you reach the last slide and you have to do a loop. Maybe when you reach the last state you're creating a new slide to push without copying the state? You're idea is interesting. What I don't understand is why it's not working only on a loop (last slide to first)

I think there is something to do because it's working perfectly for all other slides. Why all slides are sync except this one?

**Comment by bd-arc** [comment] 2017-11-09 09:40
@hugweb The problem is that I'm not able to reproduce the issue. As you can see with the screencast, and unless I'm mistaken, the issue you describe doesn't occur in your example.

One important clarification though: when looping, the data you provide is cloned in order to create slide duplicates. This is pretty complicated and a hundred lines of code are dedicated to it exclusively (you can [take a look at those](https://github.com/archriss/react-native-snap-carousel/blob/master/src/carousel/Carousel.js#L262:L359) if you're interested).

**When you reach the edges of the original slides, you are then scrolling duplicates that only share with them identical data and render method, nothing else. Any state specific to an item will not be shared with its clone.** This is linked to how `FlatList` works and the fact that you cannot handle items by themselves, only through `data` and `renderItem`.

Then, when the scroll interaction is finished, the scroll offset is seamlessly repositioned so that the original slide is presented for you to interact with.

Am I making sense?

**Comment by hugweb** [comment] 2017-11-09 10:56
Yes definitely make sense. But wait, in your screencast you don't see that the background of the page 3 when you come from the page 5 is **red** and become **green** quickly after the slide movement end?!

**Comment by bd-arc** [comment] 2017-11-09 11:21
@hugweb Of course, but that's what I've described in length ;-) When you see the red background, it's a clone. Then, immediately after scroll completion,  the `ScrollView` is repositioned to the original item (green background) on which the state has been updated.

As previously stated, there is no way to duplicate states between slides. You can only handle item with your data set and the `renderItem()` method.

Your best bet might be to update `data` whenever a change occurs and treat it accordingly in `renderItem`.

**Closed** 2017-11-16 08:42 UTC
Labels: bug
