### ISSUE TITLE
this._scrollRef.scrollTo is not a function (nested carousels)

### ISSUE THREAD

**Issue by thewolff** [archriss/react-native-snap-carousel#190] opened 2017-10-18 21:46 UTC
Hi!

I'm getting the above error when initializing my carousel! I've got the JSX for it below. 

Fun fact - I'm actually instantiating this inside something that's already within a larger Carousel component. Could that be causing the above error?

```
<Carousel
  data={heroImages}
  itemWidth={heroImageWidth}
  sliderWidth={parentCardWidth - 30}
  ref={d => {
    this._carousel = d;
  }
  renderItem={(item, idx) => {
    return (
      <View style={{ width: heroImageWidth }}>
         <Text>hi</Text>
      </View>
    );
  }}
/>
```

**Comment by bd-arc** [comment] 2017-10-19 07:16
Hi @thewolff,

Which version of the plugin are you using? Because this is supposed to be fixed in the most recent versions (starting with `3.3.0`).

**Comment by thewolff** [comment] 2017-10-19 16:18
Hi @bd-arc,

I've been using 3.3.4. Please let me know if there's any more information I can give you.

**Comment by bd-arc** [comment] 2017-10-19 16:33
My mistake, I thought this was the same issue as #166 and #167. I didn't pay attention to the fact that yours has to do with `this._scrollRef` and not `this._listRef`. Clearly, this is linked to the nested carousels template.

I remember seeing an issue about something similar in React Native's issues (accessing an underlying animated component is apparently tricky sometimes, particularly when mounting/unmounting). I also know that there are a lot of issues regarding nested `ScrollView`. Solving this might be beyond my reach if this actually has to do with RN's core. Still, I'm going to investigate.

In the meantime, can you provide me with an example that will help me reproduce the issue?

**Comment by bd-arc** [comment] 2017-10-19 16:38
Here is [the relevant line](https://github.com/facebook/react-native/blob/6747a36f5dec0c49fb32c68c8c980508e6ace7db/Libraries/Lists/VirtualizedList.js#L308) in RN `VirtualizedList`'s source code.

Do you still experience the issue if you replace this line with the following?
```
this._scrollRef && this._scrollRef.scrollTo(
```

**Comment by thewolff** [comment] 2017-10-19 16:50
Sadly no.

Even with that it's complaining that this._scrollRef.scrollTo is undefined.

**Comment by bd-arc** [comment] 2017-10-19 16:57
What about the following?
```
this._scrollRef && this._scrollRef.scrollTo && this._scrollRef.scrollTo(
```
or even the utterly ugly:
```
this._scrollRef && this._scrollRef.scrollTo && typeof this._scrollRef.scrollTo === 'function' && this._scrollRef.scrollTo(
```

This is just to make sure that the issue lies on RN's end.

Note that there are 3 occurrences of the `scrollTo()` call. The carousel should only use the one from the line I've referenced, but can you make sure to update the 3 of them?

**Comment by thewolff** [comment] 2017-10-19 17:10
Replacing it everywhere with either the first or second suggestion above allows it to render, which is great!

However, upon interaction it now throws a "Cannot read property 'onStartShouldSetRespondewrCapture' of undefined which is in Caarousel.js 620:16

**Comment by guilharj** [comment] 2017-10-19 19:02
I'm started to test nested snap Carrossel and got the same problema.  I replaced the Virtualized list code also, and I've got "onStartShouldSetRespondewrCapture" problem 

ExceptionsManager.js:73 Unhandled JS Exception: Cannot read property 'onStartShouldSetResponderCapture' of undefined

I've tried first using react-native ScrollView and worked fine, but I need a bit more responsive UI so I've tried with this lib. 

PS: I already use this project in production for a horizontal carossel and works FINE :) Thanks

**Comment by thewolff** [comment] 2017-10-19 19:21
After running into this I tried nesting FlatList inside a Carousel component and found it similarly buggy. However, as guilharj mentioned above, ScrollView seems to be fine.

**Comment by bd-arc** [comment] 2017-10-20 07:52
Unfortunately, I think that we're facing an issue that has nothing to do with the plugin :(

First, `onStartShouldSetResponderCapture` is not the carousel call (notice that, in plugin's source code, the method is called `_onStartShouldSetResponderCapture` with a `_`). It's an undocumented feature of the `ScrollView` component that exposes the underlying `PanResponder` (as you can see [here](https://github.com/facebook/react-native/blob/master/Libraries/Components/ScrollView/ScrollView.js#L802)). We're really digging deep on this one!

Then, the fact that it works with `ScrollView` but not with a `FlatList` or a `VirtualizedList` indicates that something here is broken. If I recall correctly, there are bugs with underlying `Animated` components and the nesting might be too much.

I'm pretty sure that this would work if we were to use a regular `FlatList` instead of an animated one though. If you want to try that, you need to use version `3.1.0` of the plugin and make sure that none of these props are set: `useNativeOnScroll`, `hasParallaxImages`, and `scrollEventThrottle`.

**Comment by bd-arc** [comment] 2017-10-23 07:57
@thewolff @guilharj Did any of you guys had time to try nested carousels with version `3.1.0`?

**Comment by bd-arc** [comment] 2017-10-27 08:53
Closing as no further feedback was provided.

**Closed by bd-arc** 2017-10-27 08:53 UTC
Labels: feedback?

**Comment by WonderDev21** [comment] 2018-01-12 00:52
I tried to use nested carousel version 3.1.0, but I failed.
What is the solution?

**Comment by bd-arc** [comment] 2018-01-12 08:23
Unfortunately, we can't be sure that a solution can be found since the issue comes from the `FlatList` component and not from the plugin.

Note that [a prop `useScrollView`](https://github.com/archriss/react-native-snap-carousel/#behavior) has been introduced in version `3.5.0`. I recommend that you try to activate it for both your carousels; maybe the issue won't show up when using an animated `ScrollView` instead of an animated `FlatList`.

If you need us to dig deeper into the issue, please create an example that reproduces the bug using https://snack.expo.io/ and provide us with the link.

**Comment by VitaliiK91** [comment] 2018-03-23 00:10
useScrollView for nested carousel worked in my case. Thanks @bd-arc

**Comment by Hallyson10** [comment] 2020-05-27 02:54
desestruture the carrosel in componentDidMount : const { carrosel } = this.state

**Comment by Eramirez06** [comment] 2020-09-04 23:20
any update with this?

**Comment by abedolinger** [comment] 2022-04-07 23:01
Thank you @thewolff, I'm fortunate enough to be able to use a ScrollView inside my nested carousel, so adding `useScrollView` to my carousel props works perfectly!
