### ISSUE TITLE
https://github.com/meliorence/react-native-snap-carousel

### ISSUE THREAD

**Issue by pateljinal1844** [archriss/react-native-snap-carousel#860] opened 2021-08-27 10:07 UTC

**Comment by flexbox** [comment] 2021-09-27 15:45
Duplicate of #861 

@pateljinal1844 
Can you please close the issue? 
It sparks joy for maintainers ✨

**Comment by pateljinal1844** [comment] 2021-10-05 13:18
Added space in subview

**Closed as completed** 2021-10-05 13:17 UTC
