### ISSUE TITLE
Customizing the scrolling animation

### ISSUE THREAD

**Issue by iChriiss** [archriss/react-native-snap-carousel#217] opened 2017-11-15 06:12 UTC
### Is this a bug report or a feature request?

Question/Help

Thanks for this Awesome component! :)
Is it possible to alter the swiping animation? The current animation makes it such that the carousel item does not have a consistent speed (Im assuming this is to give it the appearance of a carousel, where the item sort of swings towards you, before continuing ). Im curious to know if I could make it so that the speed is consistent throughout the length of the animation

Thanks!

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel#reporting-an-issue) regarding bug report?

(Write your answer here.)

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

(Write your answer here.)

### Have you made sure that your issue hasn't already been reported/solved?

(Write your answer here.)

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

(Write your answer here.)

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

(Write your answer here.)

### Environment

(Write your answer here.)

### Steps to Reproduce

(Write your steps here:)

1.
2.
3.

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screencasts/screenshots!)

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by bd-arc** [comment] 2017-11-15 09:55
Hi @iChriiss,

Your question is a duplicate of #213.

This is not by design; it's rooted in the fact that the `ScrollView` component upon which the plugin is ultimately based [doesn't offer any kind of animation speed option](https://github.com/archriss/react-native-snap-carousel/#flatlist-and-scrollviews-limitations).

Two currently opened issues might be of interest for you though:
- **#203: in which I've listed React Native's Canny issues on which everyone can vote to put the focus on the most needed evolutions** ;-)
- #189: in which I've explained the problem and talked about incoming attempts to implement `pagingEnabled` and `snapToInterval` in order to smooth things out on iOS.

**Closed by bd-arc** 2017-11-15 09:55 UTC
