### ISSUE TITLE
snapToItem(0, (animated = false)) snaps to SECOND item.

### ISSUE THREAD

**Issue by rendomnet** [archriss/react-native-snap-carousel#199] opened 2017-10-28 16:37 UTC
Cant snap to first item.
`this._carousel.snapToItem(0, (animated = true)); ` snaps to second one.
And `this._carousel.snapToItem(1, (animated = true));` snaps to third one.

**Comment by bd-arc** [comment] 2017-10-28 17:00
@rendomnet Can you share your exact `<Carousel />` set up?

**Comment by rendomnet** [comment] 2017-10-28 17:05
```
<Carousel
            ref={c => {
              this._carousel = c;
            }}
            loop={true}
            apparitionDelay={500}
            data={this.state.markers}
            renderItem={this._renderCarouselItem}
            sliderWidth={DEVICE_WIDTH}
            firstItem={0}
            itemWidth={CARD_WIDTH}
            inactiveSlideOpacity={0.8}
            autoplay={false}
            inactiveSlideScale={0.9}
            enableMomentum={true}
            onSnapToItem={index => this.carouselSnap(index)}
            activeSlideAlignment="center"
            autoplayDelay={0}
            containerCustomStyle={styles.cardContainer}
            contentContainerCustomStyle={{}}
          />
```
```
  carouselSnap(index) {
    const { coordinate } = this.state.markers[index];
    this.map.animateToRegion(
      {
        ...coordinate,
        latitudeDelta: this.state.region.latitudeDelta,
        longitudeDelta: this.state.region.longitudeDelta
      },
      350
    );
  }

```
```
 markerClick(index) {
     this._carousel.snapToItem(index, true);
  }
```

**Comment by bd-arc** [comment] 2017-10-28 19:18
@rendomnet This might have to do with the `loop` feature. Does it work properly if you set `loop` to `false`?

**Comment by rendomnet** [comment] 2017-10-29 04:57
@bd-arc  Yes. Turning off loop makes snapToItem act properly. But we need fix for loop=true settings.

**Comment by bd-arc** [comment] 2017-11-01 22:31
The issue should be fixed by [this commit](https://github.com/archriss/react-native-snap-carousel/commit/6fca99c341de5d16f474d3eda591a35597c18b15). To try it out, just copy/paste the following in your `package.json` file:
```
"react-native-snap-carousel": "https://github.com/archriss/react-native-snap-carousel#ce3bf06"
```

@rendomnet Can you confirm that it works for you?

@WienerGames I've implemented the fix that we've discussed in private, while trying to guard against a few potential issues. Let me know if this looks legit to you ;-)

**Comment by bd-arc** [comment] 2017-11-06 15:13
Closing as no further feedback was provided.
The supposed fix has been published in version `3.4.0`.

**Closed by bd-arc** 2017-11-06 15:13 UTC
Labels: bug, feedback?

**Comment by rendomnet** [comment] 2017-11-06 15:16
@bd-arc sorry my PC is not available rn so cant test your solution. I think it will work anyway, thank you for response.

**Comment by jordangrant** [comment] 2017-12-06 03:58
@bd-arc Potential bug: Have been using a **looped** carousel, and let's say I start at index one, I move to the left (index 0.. index (-1)..) the carousel suddenly loops around to that same card, but on the right side? Hard to explain, here's a gif: https://imgur.com/61cmLGJ
Quite a bit of skipping, in general, looking at the commit above, I'm thinking it _could_ be related?

**Comment by bd-arc** [comment] 2017-12-06 08:46
Hi @jordangrant,

Thanks for reporting back. While the issue you describe is not linked to the one from this thread, it clearly has to do with loop handling.

When looping, the data you provide is cloned in order to create slide duplicates. When you reach the edges of the original slides, you are then scrolling duplicates (their number being defined by prop `loopClonesPerSide`). Then, when the scroll interaction is finished, the scroll offset is seamlessly repositioned so that the original slide is presented for you to interact with.


They are two potential problems though:
- **On Android in debug mode**, and while the repositioning is done without animation, you can sometimes see the carousel moving. There is nothing I can do about it since that's an issue with the underlying `FlatList` component (have you seen [this](https://github.com/archriss/react-native-snap-carousel/issues/203) by the way? ;-)). This problem usually goes away in production mode.
- Depending on the number of slides you're dealing with, the `FlatList` will do its internal optimizations and avoid rendering slides that are "too far away". When the carousel is repositioned, you might then be facing a temporary blank slide... You can try modifying [inherited props](https://github.com/archriss/react-native-snap-carousel/#inherited-props)'s default values to find something that better suits your need. I'm starting to wonder whether I should add a prop to prevent optimizations by rendering a `ScrollView` instead of a `FlatList`.

**Comment by bd-arc** [comment] 2017-12-06 08:47
Honestly, I'm not completely satisfied with the "clones" approach, but that's the only one I could think of with the `FlatList` component  in which rendering can only be handled with `data` and `renderItem()`.

If you have a better idea, I'll be glad to implement it ;-)

**Comment by AmmarTariq10** [comment] 2018-10-16 09:52
snaptoprev and snaptoItem(0) both are not working I want to slide back to the first item
here is how I'm creating my carousel
 <Carousel
                        onSnapToItem={(slideIndex)=>{
                            console.log('slideIndex')
                            EventRegister.emit('goHard:segmentChange')
                            this.setState(p=>{
                                return{
                                    ...p,
                                    index:slideIndex
                                }
                            })
                        console.log(this.state.index,pos)
                        }}  
                        loop={false}
                        slideStyle={{width:90*vw}}
                        ref={(c) => { this._carousel = c; }}
                        data={this.state.data}
                        renderItem={this._renderItem}
                        sliderWidth={100 * vw}
                        itemWidth={100 * vw}
                        inactiveSlideScale={1}
                        swipeThreshold={40 * vw}
                        inactiveSlideOpacity={1}
                        activeSlideAlignment={pos}
                    />

**Comment by bd-arc** [comment] 2018-10-16 12:40
@AmmarTariq10 Please create a new thread that includes a Snack example in which the issue can be reproduced. Make sure to follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).

**Comment by sultan-arshi** [comment] 2019-09-17 21:05
for me `(animated = true)` worked but when I used `(animated = false)` it returns to previous image 
I don't know why 
I think this bug still present in the library
