### ISSUE TITLE
Swiper freezes on second slide.

### ISSUE THREAD

**Issue by dpogoda** [archriss/react-native-snap-carousel#392] opened 2018-09-12 14:46 UTC
### Is this a bug report, a feature request, or a question?

Bug report

### Have you followed the required steps before opening a bug report?

- [x] I have read [the guidelines regarding bug report](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md).
- [x] I have reviewed [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/archriss/react-native-snap-carousel/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/archriss/react-native-snap-carousel/releases).
- [x] I am following [the issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md) closely in order to produce a useful bug report.

### Have you made sure that it wasn't a [React Native bug](https://github.com/archriss/react-native-snap-carousel/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22react-native+bug%22+)?

Yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both iOS and Android

### Is the bug reproductible in a production environment (not a debug one)?

Yes.

### Environment

| software         | version
| ---------------- | -------
| react | 16.5.0
| react-native     | 0.56.1
| react-native-snap-carousel    | 3.7.3
| Target     |     Android (6.0)
| Target     |     iOS (9.0)

### Expected Behavior

The swiper should be swipeable. If downgrading and fixing to `react-native-snap-carousel 3.7.2` it works as expected.

### Actual Behavior

After updating the `yarn.lock` file, the swiper broke in our app. We could swipe to the second slide, but then it froze. We could neither slide forward nor backward. Interactions (e.g. links) on the current slide still work.

### Reproducible Demo

Unfortunately I couldn't reproduce this bug in a minimal app. Everything worked fine. I'll continue to work on a reproduction and update this issue.

Does anybody else have similar problems or a setup where the carousel breaks with the latest `react-native-snap-carousel` version? I'd appreciate if someone could confirm the issue or help me resolve it.

**Comment by bd-arc** [comment] 2018-09-12 21:36
Hi @dpogoda,

The bug might be linked to PR #390. Does it work properly if you remove [the added line](https://github.com/archriss/react-native-snap-carousel/pull/390/files)?

**Comment by dpogoda** [comment] 2018-09-13 11:45
@bd-arc 
Thanks for the fast reply. Yes in fact deleting that line fixes the issue :)

**Comment by bd-arc** [comment] 2018-09-13 13:03
Well, I should have tested the PR myself... Ok, I'll try and fix it as soon as I can.

Thanks for the feedback ;-)

**Comment by dpogoda** [comment] 2018-09-13 13:33
@bd-arc  Thank you for this amazing react native component :-)

**Comment by bd-arc** [comment] 2018-09-13 19:52
@dpogoda Should be fixed in version `3.7.4` ;-)

**Comment by bd-arc** [comment] 2018-10-01 08:10
@benobab Damn! Could you share the configuration of your carousel?

**Comment by benobab** [comment] 2018-10-01 09:29
Thanks for the reply!

Tell me if the code below is enough

```js
                          <Carousel layout={'stack'} 
                                    data={ENTRIES}
                                    renderItem={this._renderItem}
                                    sliderWidth={sliderWidth}
                                    itemWidth={itemWidth}
                                    hasParallaxImages={false}
                                    firstItem={this.state.sliderActiveSlide}
                                    inactiveSlideScale={0.95}
                                    inactiveSlideOpacity={0.7}
                                    containerCustomStyle={styles.slider}
                                    contentContainerCustomStyle={styles.sliderContentContainer}
                                    loop={true}
                                    autoplay={false}
                                    // autoplayDelay={500}
                                    // autoplayInterval={3000}
                                    onSnapToItem={(index) => this.setState({ sliderActiveSlide: index }) }
                                />
```

**Comment by benobab** [comment] 2018-10-01 09:30
The problem doesn't appear in the default mode.

**Comment by bd-arc** [comment] 2018-10-01 09:45
@benobab This is interesting. Have you been able to isolate the prop responsible for the bug appearance then?

**Comment by Zyphxion** [comment] 2018-10-01 18:07
I am also encountering a similar issue, however it's only appearing on Android.  The slider is unable to be moved when swiping.  Autoplay seems to work, and the elements are clickable, just swiping seems to be busted.

My configuration:
`<Carousel
          ref={(c) => { this._carousel = c; }}
          data={this.props.items}
          renderItem={this.singleItem}
          sliderWidth={Dimensions.get('window').width}
          itemWidth={Dimensions.get('window').width * 0.4}
          inactiveSlideScale={0.7}
          loop={true}
          enableSnap={true}
        />`

**Comment by bd-arc** [comment] 2018-10-01 20:50
@benobab @Zyphxion Can you tell me if this works properly when you use version `3.7.2`?

**Comment by harrison0723** [comment] 2018-10-03 07:01
Not to complicate things further, but I encounter a similar issue which only happens on iOS, the third swipe would freeze...

**Comment by bd-arc** [comment] 2018-10-03 08:16
@harrison0723 Same question: does it work properly if you use version `3.7.2`?

**Comment by harrison0723** [comment] 2018-10-03 08:18
@bd-arc Nope, same issue with `3.7.2` for me

**Comment by harrison0723** [comment] 2018-10-03 08:33
@bd-arc So sorry I've decided to switch to another library due to the Android inverted issue :-( This library seems pretty amazing though, hope this issue can be resolved soon

**Comment by bd-arc** [comment] 2018-10-05 09:58
This has been fixed in version `3.7.5` thanks to @ifsnow. Kudos to him!

**Closed by bd-arc** 2018-10-05 09:58 UTC
Labels: bug

**Comment by harrison0723** [comment] 2018-10-11 10:15
For anyone who still seems to have a similar issue, `removeClippedSubviews={false}` might solve your problem.

**Comment by harisbaig100** [comment] 2021-08-20 12:05
`loopClonesPerSide={data.length}` this prop is by default '3', setting it to length of the data will solve the stuck issue.

**Comment by brambang** [comment] 2021-09-22 08:21
in terms of performance which is better?
`removeClippedSubviews={false}`
or
`loopClonesPerSide={data.length}`

removeClippedSubviews set to false would impact performance in flatlist
loopClonesPerSide to data.length would make 3 times images load

UPDATE:
both of that not works

**Comment by mustafaaii** [comment] 2024-06-14 00:44
I was getting this issue in React JS and React Native. However, I found a strange solution to this. If you put Swiper in a component and activate it at the first startup, the problem is solved, the example is below.

```
const Carousel = ({ data }: any) => {

        return (
            <>
                <Swiper autoplay={true} loop={true} showsButtons={false} showsPagination={false} style={{ height: 330 }} removeClippedSubviews={false}>
                    {
                        (Media(data.filter((f: any) => { return (f.type === type && f.page === page && f.position === position) })) || []).map((d: any, x: number) => {
                            return (
                                <View key={`banner-${d.id}-list-${x}`}>
                                    <TouchableOpacity onPress={() => { Linking.openURL(d.url); }}>
                                        <Image source={{ uri: `https://ik.imagekit.io/tey21emoa/banner/${d.blob}` }} style={{ resizeMode: "stretch", height: 330, width: "100%", borderRadius: 8, borderWidth: 1, borderColor: "#dee2e6" }} />
                                    </TouchableOpacity>
                                </View>
                            )
                        })
                    }
                </Swiper>
            </>
        )
    }
```
