### ISSUE TITLE
Carouse Item can't handle press event

### ISSUE THREAD

**Issue by JetQin** [archriss/react-native-snap-carousel#245] opened 2018-01-16 03:40 UTC
```
<View key={index} style={styles.slide}>
                <TouchableOpacity style={styles.slideInnerContainer} onPress={this.gotoPay} >
                    <Image
                        source={{ uri: item.url }}
                        style={styles.image}
                    />
                </TouchableOpacity>
 </View>
```
here is the renderItem code, when I click the item , it didn't give me any response

**Comment by bd-arc** [comment] 2018-01-16 08:50
**⚠️ You did not follow [the contributing guidelines](https://github.com/archriss/react-native-snap-carousel/blob/master/CONTRIBUTING.md)!**

As stated in these:
> :warning: You need to fill out the [issue template](https://raw.githubusercontent.com/archriss/react-native-snap-carousel/master/ISSUE_TEMPLATE.md). **This step is mandatory!** Not doing so will result in your issue getting closed. Don't take this personally if this happens, and feel free to open a new issue once you've gathered all the information required by the template.

---

**Unless you provide a [Snack example](https://snack.expo.io/) that reproduces the issue, we won't be able to help you and the issue will be closed.**

**Comment by bd-arc** [comment] 2018-01-18 08:32
Closing as no further feedback was provided.

**Closed by bd-arc** 2018-01-18 08:32 UTC
Labels: contribution?, reproduction?

**Comment by SKempin** [comment] 2018-06-09 20:36
I can confirm that a carousel item _can_ handle an onPress event - tested in `3.7.0`

**Comment by alexlevy0** [comment] 2018-07-18 18:10
+1

**Comment by yjb94** [comment] 2019-04-19 02:53
check if your renderItem function is an arrow function or binded. that might cause this issue

**Comment by oferRounds** [comment] 2019-05-22 08:20
Seeing this also, has anyone found the causes for this?

**Comment by oferRounds** [comment] 2019-05-22 09:06
@JetQin did you find solution to this?

**Comment by yjb94** [comment] 2019-05-22 10:40
@oferRounds check your renderItem function. if it's somewhat like `_renderItem ({item, index})` it should be changed like `_renderItem = ({item, index}) =>`

**Comment by oferRounds** [comment] 2019-05-22 11:23
@yjb94 thanks! It seems ok as far as I can tell - wdyt?
```
<Carousel
              data = { this.props.policies }
              renderItem = { this.renderSlide }
              sliderWidth = { Dimensions.get('window').width }
              temWidth = { ITEM_WIDTH }
              ref = { this.onGetSliderRef }
              containerCustomStyle = { styles.slider }
              contentContainerCustomStyle = { styles.sliderContentContainer }
              loop = { true }
              onSnapToItem = { this.onSnapToItem }
 />

```
private renderSlide = ({ item }) => {
        return (
            <TimeOffPolicySlide
                key = { (item as TimeOffPolicyModel).type }
                policy = { item } userGender = { this.props.userGender }
                width = { ITEM_WIDTH } height = { ITEM_HEIGHT }
                onRequestButtonPress = { this.onRequestTimeOffButtonPress }
            />
        )
    }
```
