### ISSUE TITLE
Invariant Violation: No item for index..

### ISSUE THREAD

**Issue by ethanyuwang** [archriss/react-native-snap-carousel#220] opened 2017-11-18 00:46 UTC
### Is this a bug report or a feature request?

bug report

### Have you read [the guidelines](https://github.com/archriss/react-native-snap-carousel#reporting-an-issue) regarding bug report?

(Write your answer here.)

### Have you read [the documentation](https://github.com/archriss/react-native-snap-carousel/blob/master/README.md) in its entirety?

yes

### Have you made sure that your issue hasn't already been reported/solved?

yes

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

(Write your answer here and specify the iOS/Android versions on which you've been able to reproduce the issue.)

### Is the bug reproductible in a production environment (not a debug one)?

(Write your answer here.)

### Have you been able to reproduce the bug in [the provided example](https://github.com/archriss/react-native-snap-carousel/tree/master/example)?

(Write your answer here.)

### Environment

Environment:
  OS: macOS High Sierra 10.13.1
  Node: 6.11.3
  Yarn: Not Found
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: Xcode 9.1 Build version 9B55
  Android Studio: 2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.0.0-beta.5 => 16.0.0-beta.5
  react-native: ^0.49.5 => 0.49.5

### Steps to Reproduce

(Write your steps here:)

I have declared a carousel following the example code as below:

```
<Carousel
          ref={(c) => { this._carousel = c; }}
          data={this.state.resumeList}
          extraData={this.state}
          renderItem={this._renderResume}
          inactiveSlideScale={1}
          sliderWidth={width}
          itemWidth={width*RESUME_SCALE+HORIZONTAL_MARGIN*2}
          onSnapToItem={(slideIndex) => this.setState({activeResumeIndex: slideIndex-1})}
/>
```

### Expected Behavior

Items are rendered

### Actual Behavior

Most of the time items are rendered just fine, but occasionallly I'd get this error. the index sometimes is 1 or 3. I have tried to look up the error but found none. What could be the reason for this error?

![simulator screen shot - iphone 8 - 2017-11-17 at 16 36 11](https://user-images.githubusercontent.com/17556945/32974849-93621070-cbb6-11e7-8369-21648b65359c.png)

### Reproducible Demo

(Paste the link to an example project or paste the entirety of the relevant source code. Then provide instructions to reproduce the issue.)

**Comment by bd-arc** [comment] 2017-11-20 10:34
Hi @ethanyuwang,

Unfortunately, I am not able to reproduce the issue. It would really help if you could provide a complete example.

**Comment by lc3t35** [comment] 2017-11-24 11:45
what do you do with 
````
onSnapToItem={(slideIndex) => this.setState({activeResumeIndex: slideIndex-1})}
````
It can be negative when slideIndex is 0 ....

**Comment by bd-arc** [comment] 2017-11-28 09:17
Closing as no further feedback was provided.

**Closed by bd-arc** 2017-11-28 09:17 UTC
Labels: feedback?, reproduction?
