### ISSUE TITLE
"Cannot read property 'stopTracking' of undefined " how to solve

### ISSUE THREAD

**Issue by thepinyo** [archriss/react-native-snap-carousel#62] opened 2017-05-04 06:29 UTC

**Comment by bd-arc** [comment] 2017-05-04 08:01
Hi @thepinyo, could you please provide a bit more context and could you describe a way to reproduce the issue?

**Comment by bd-arc** [comment] 2017-05-15 20:47
Closing as no further feedback was provided.

**Comment by fdwcomune** [comment] 2017-05-25 06:22
Hi, I also got this issue recently. In my case it happened when changing the number of carousel items. When the active item index before the change is greater than the highest possible index after the change the error is thrown.

**Comment by bd-arc** [comment] 2017-05-26 18:49
Hi @fdwcomune and thanks for the detailed info.

Note that many currently opened issues seem to be related to component's state management, meaning that we apparently need to improve it. I'll take a closer look at this matter shortly.

**Comment by Venumteam** [comment] 2017-05-29 10:00
Hey guys, had the same issue - when trying to remove the item from items, hope that soon it will be fixed.

**Comment by arnsa** [comment] 2017-06-01 10:05
https://github.com/archriss/react-native-snap-carousel/pull/67 this PR fixes the issue.

**Comment by bd-arc** [comment] 2017-06-03 20:49
Hi guys,

I'm currently working on fixing the issue. @fdwcomune @Venumteam Would you mind sharing some code in order to help me reproduce the bug? So far, I haven't been able to do so.

FYI I won't merge #67 for now since the fix is, in my opinion, a bit hacky. Moreover, it will work only if a single item was removed. I'm trying to find another solution, but I might be mistaken since I haven't reproduced the bug yet. Thoughts are very welcome ;-)

**Comment by bd-arc** [comment] 2017-06-05 10:06
Linked to #66

**Comment by kylanhurt** [comment] 2017-06-07 18:58
Make sure that you use the `<Animated._____>` part of that tag. I've gotten similar issues for trying to animate a `<View>` instead of `<Animated.View>`

**Comment by bd-arc** [comment] 2017-06-16 09:24
Hi guys! Version 2.3.0 should solve this issue.

Let me know if you still have problem with this.

**Closed by bd-arc** 2017-06-16 09:24 UTC
Labels: bug, reproduction?
